FROM python:3.11-slim

WORKDIR /back

COPY back/ /back/

COPY requirements.txt /back/

RUN pip install -r requirements.txt

EXPOSE 8000

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]